// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.11
// source: inventory/v1/message.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_inventory_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_inventory_v1_message_proto_rawDescGZIP(), []int{0}
}

type GoodsInvInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodsId       int32                  `protobuf:"varint,1,opt,name=goodsId,proto3" json:"goodsId,omitempty"`
	Num           int32                  `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsInvInfo) Reset() {
	*x = GoodsInvInfo{}
	mi := &file_inventory_v1_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsInvInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsInvInfo) ProtoMessage() {}

func (x *GoodsInvInfo) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsInvInfo.ProtoReflect.Descriptor instead.
func (*GoodsInvInfo) Descriptor() ([]byte, []int) {
	return file_inventory_v1_message_proto_rawDescGZIP(), []int{1}
}

func (x *GoodsInvInfo) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *GoodsInvInfo) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type SellInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodsInfo     []*GoodsInvInfo        `protobuf:"bytes,1,rep,name=goodsInfo,proto3" json:"goodsInfo,omitempty"`
	OrderSn       string                 `protobuf:"bytes,2,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SellInfo) Reset() {
	*x = SellInfo{}
	mi := &file_inventory_v1_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SellInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SellInfo) ProtoMessage() {}

func (x *SellInfo) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SellInfo.ProtoReflect.Descriptor instead.
func (*SellInfo) Descriptor() ([]byte, []int) {
	return file_inventory_v1_message_proto_rawDescGZIP(), []int{2}
}

func (x *SellInfo) GetGoodsInfo() []*GoodsInvInfo {
	if x != nil {
		return x.GoodsInfo
	}
	return nil
}

func (x *SellInfo) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

var File_inventory_v1_message_proto protoreflect.FileDescriptor

const file_inventory_v1_message_proto_rawDesc = "" +
	"\n" +
	"\x1ainventory/v1/message.proto\x12\x14service.inventory.v1\"\a\n" +
	"\x05Empty\":\n" +
	"\fGoodsInvInfo\x12\x18\n" +
	"\agoodsId\x18\x01 \x01(\x05R\agoodsId\x12\x10\n" +
	"\x03num\x18\x02 \x01(\x05R\x03num\"f\n" +
	"\bSellInfo\x12@\n" +
	"\tgoodsInfo\x18\x01 \x03(\v2\".service.inventory.v1.GoodsInvInfoR\tgoodsInfo\x12\x18\n" +
	"\aorderSn\x18\x02 \x01(\tR\aorderSnBS\n" +
	"\"service.inventory.api.inventory.v1P\x01Z+mshop/service/inventory/api/inventory/v1;v1b\x06proto3"

var (
	file_inventory_v1_message_proto_rawDescOnce sync.Once
	file_inventory_v1_message_proto_rawDescData []byte
)

func file_inventory_v1_message_proto_rawDescGZIP() []byte {
	file_inventory_v1_message_proto_rawDescOnce.Do(func() {
		file_inventory_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_v1_message_proto_rawDesc), len(file_inventory_v1_message_proto_rawDesc)))
	})
	return file_inventory_v1_message_proto_rawDescData
}

var file_inventory_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_inventory_v1_message_proto_goTypes = []any{
	(*Empty)(nil),        // 0: service.inventory.v1.Empty
	(*GoodsInvInfo)(nil), // 1: service.inventory.v1.GoodsInvInfo
	(*SellInfo)(nil),     // 2: service.inventory.v1.SellInfo
}
var file_inventory_v1_message_proto_depIdxs = []int32{
	1, // 0: service.inventory.v1.SellInfo.goodsInfo:type_name -> service.inventory.v1.GoodsInvInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_inventory_v1_message_proto_init() }
func file_inventory_v1_message_proto_init() {
	if File_inventory_v1_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_v1_message_proto_rawDesc), len(file_inventory_v1_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_inventory_v1_message_proto_goTypes,
		DependencyIndexes: file_inventory_v1_message_proto_depIdxs,
		MessageInfos:      file_inventory_v1_message_proto_msgTypes,
	}.Build()
	File_inventory_v1_message_proto = out.File
	file_inventory_v1_message_proto_goTypes = nil
	file_inventory_v1_message_proto_depIdxs = nil
}
