// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.11
// source: inventory/v1/service.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_inventory_v1_service_proto protoreflect.FileDescriptor

const file_inventory_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1ainventory/v1/service.proto\x12\x14service.inventory.v1\x1a\x1ainventory/v1/message.proto\x1a\x1cgoogle/api/annotations.proto2\xb6\x03\n" +
	"\tInventory\x12g\n" +
	"\x06SetInv\x12\".service.inventory.v1.GoodsInvInfo\x1a\x1b.service.inventory.v1.Empty\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/inventory/set\x12t\n" +
	"\tInvDetail\x12\".service.inventory.v1.GoodsInvInfo\x1a\".service.inventory.v1.GoodsInvInfo\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/inventory/{goodsId}\x12b\n" +
	"\x04Sell\x12\x1e.service.inventory.v1.SellInfo\x1a\x1b.service.inventory.v1.Empty\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/inventory/sell\x12f\n" +
	"\x06Reback\x12\x1e.service.inventory.v1.SellInfo\x1a\x1b.service.inventory.v1.Empty\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/inventory/rebackBS\n" +
	"\"service.inventory.api.inventory.v1P\x01Z+mshop/service/inventory/api/inventory/v1;v1b\x06proto3"

var file_inventory_v1_service_proto_goTypes = []any{
	(*GoodsInvInfo)(nil), // 0: service.inventory.v1.GoodsInvInfo
	(*SellInfo)(nil),     // 1: service.inventory.v1.SellInfo
	(*Empty)(nil),        // 2: service.inventory.v1.Empty
}
var file_inventory_v1_service_proto_depIdxs = []int32{
	0, // 0: service.inventory.v1.Inventory.SetInv:input_type -> service.inventory.v1.GoodsInvInfo
	0, // 1: service.inventory.v1.Inventory.InvDetail:input_type -> service.inventory.v1.GoodsInvInfo
	1, // 2: service.inventory.v1.Inventory.Sell:input_type -> service.inventory.v1.SellInfo
	1, // 3: service.inventory.v1.Inventory.Reback:input_type -> service.inventory.v1.SellInfo
	2, // 4: service.inventory.v1.Inventory.SetInv:output_type -> service.inventory.v1.Empty
	0, // 5: service.inventory.v1.Inventory.InvDetail:output_type -> service.inventory.v1.GoodsInvInfo
	2, // 6: service.inventory.v1.Inventory.Sell:output_type -> service.inventory.v1.Empty
	2, // 7: service.inventory.v1.Inventory.Reback:output_type -> service.inventory.v1.Empty
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_inventory_v1_service_proto_init() }
func file_inventory_v1_service_proto_init() {
	if File_inventory_v1_service_proto != nil {
		return
	}
	file_inventory_v1_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_v1_service_proto_rawDesc), len(file_inventory_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventory_v1_service_proto_goTypes,
		DependencyIndexes: file_inventory_v1_service_proto_depIdxs,
	}.Build()
	File_inventory_v1_service_proto = out.File
	file_inventory_v1_service_proto_goTypes = nil
	file_inventory_v1_service_proto_depIdxs = nil
}
