// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.11
// source: goods/v1/message.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Empty 消息类型，用于不需要返回数据的 RPC 调用
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_goods_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_goods_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_goods_v1_message_proto_rawDescGZIP(), []int{0}
}

// 分类列表请求
type CategoryListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`       // 分类ID
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"` // 分类层级
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryListRequest) Reset() {
	*x = CategoryListRequest{}
	mi := &file_goods_v1_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryListRequest) ProtoMessage() {}

func (x *CategoryListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goods_v1_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryListRequest.ProtoReflect.Descriptor instead.
func (*CategoryListRequest) Descriptor() ([]byte, []int) {
	return file_goods_v1_message_proto_rawDescGZIP(), []int{1}
}

func (x *CategoryListRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CategoryListRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

// 分类信息请求
type CategoryInfoRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                         // 分类ID
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                      // 分类名称
	ParentCategory int32                  `protobuf:"varint,3,opt,name=parentCategory,proto3" json:"parentCategory,omitempty"` // 父分类ID
	Level          int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`                   // 分类层级
	IsTab          bool                   `protobuf:"varint,5,opt,name=isTab,proto3" json:"isTab,omitempty"`                   // 是否为标签页
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CategoryInfoRequest) Reset() {
	*x = CategoryInfoRequest{}
	mi := &file_goods_v1_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryInfoRequest) ProtoMessage() {}

func (x *CategoryInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goods_v1_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryInfoRequest.ProtoReflect.Descriptor instead.
func (*CategoryInfoRequest) Descriptor() ([]byte, []int) {
	return file_goods_v1_message_proto_rawDescGZIP(), []int{2}
}

func (x *CategoryInfoRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CategoryInfoRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryInfoRequest) GetParentCategory() int32 {
	if x != nil {
		return x.ParentCategory
	}
	return 0
}

func (x *CategoryInfoRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CategoryInfoRequest) GetIsTab() bool {
	if x != nil {
		return x.IsTab
	}
	return false
}

// 删除分类请求
type DeleteCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 要删除的分类ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCategoryRequest) Reset() {
	*x = DeleteCategoryRequest{}
	mi := &file_goods_v1_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCategoryRequest) ProtoMessage() {}

func (x *DeleteCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goods_v1_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCategoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteCategoryRequest) Descriptor() ([]byte, []int) {
	return file_goods_v1_message_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteCategoryRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 查询分类请求
type QueryCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`    // 分类ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // 分类名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryCategoryRequest) Reset() {
	*x = QueryCategoryRequest{}
	mi := &file_goods_v1_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryCategoryRequest) ProtoMessage() {}

func (x *QueryCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goods_v1_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryCategoryRequest.ProtoReflect.Descriptor instead.
func (*QueryCategoryRequest) Descriptor() ([]byte, []int) {
	return file_goods_v1_message_proto_rawDescGZIP(), []int{4}
}

func (x *QueryCategoryRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *QueryCategoryRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 分类信息响应
type CategoryInfoResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                         // 分类ID
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                      // 分类名称
	ParentCategory int32                  `protobuf:"varint,3,opt,name=parentCategory,proto3" json:"parentCategory,omitempty"` // 父分类ID
	Level          int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`                   // 分类层级
	IsTab          bool                   `protobuf:"varint,5,opt,name=isTab,proto3" json:"isTab,omitempty"`                   // 是否为标签页
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CategoryInfoResponse) Reset() {
	*x = CategoryInfoResponse{}
	mi := &file_goods_v1_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryInfoResponse) ProtoMessage() {}

func (x *CategoryInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goods_v1_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryInfoResponse.ProtoReflect.Descriptor instead.
func (*CategoryInfoResponse) Descriptor() ([]byte, []int) {
	return file_goods_v1_message_proto_rawDescGZIP(), []int{5}
}

func (x *CategoryInfoResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CategoryInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CategoryInfoResponse) GetParentCategory() int32 {
	if x != nil {
		return x.ParentCategory
	}
	return 0
}

func (x *CategoryInfoResponse) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CategoryInfoResponse) GetIsTab() bool {
	if x != nil {
		return x.IsTab
	}
	return false
}

// 分类列表响应
type CategoryListResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Total         int32                   `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`      // 总数
	Data          []*CategoryInfoResponse `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`         // 分类数据列表
	JsonData      string                  `protobuf:"bytes,3,opt,name=jsonData,proto3" json:"jsonData,omitempty"` // JSON格式数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryListResponse) Reset() {
	*x = CategoryListResponse{}
	mi := &file_goods_v1_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryListResponse) ProtoMessage() {}

func (x *CategoryListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goods_v1_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryListResponse.ProtoReflect.Descriptor instead.
func (*CategoryListResponse) Descriptor() ([]byte, []int) {
	return file_goods_v1_message_proto_rawDescGZIP(), []int{6}
}

func (x *CategoryListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CategoryListResponse) GetData() []*CategoryInfoResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CategoryListResponse) GetJsonData() string {
	if x != nil {
		return x.JsonData
	}
	return ""
}

// 子分类列表响应
type SubCategoryListResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Total         int32                   `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`              // 总数
	Info          *CategoryInfoResponse   `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`                 // 父分类信息
	SubCategorys  []*CategoryInfoResponse `protobuf:"bytes,3,rep,name=subCategorys,proto3" json:"subCategorys,omitempty"` // 子分类列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubCategoryListResponse) Reset() {
	*x = SubCategoryListResponse{}
	mi := &file_goods_v1_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubCategoryListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubCategoryListResponse) ProtoMessage() {}

func (x *SubCategoryListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goods_v1_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubCategoryListResponse.ProtoReflect.Descriptor instead.
func (*SubCategoryListResponse) Descriptor() ([]byte, []int) {
	return file_goods_v1_message_proto_rawDescGZIP(), []int{7}
}

func (x *SubCategoryListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *SubCategoryListResponse) GetInfo() *CategoryInfoResponse {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *SubCategoryListResponse) GetSubCategorys() []*CategoryInfoResponse {
	if x != nil {
		return x.SubCategorys
	}
	return nil
}

// 品牌分类过滤请求
type CategoryBrandFilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pages         int32                  `protobuf:"varint,1,opt,name=pages,proto3" json:"pages,omitempty"`             // 页码
	PagePerNums   int32                  `protobuf:"varint,2,opt,name=pagePerNums,proto3" json:"pagePerNums,omitempty"` // 每页数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryBrandFilterRequest) Reset() {
	*x = CategoryBrandFilterRequest{}
	mi := &file_goods_v1_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryBrandFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryBrandFilterRequest) ProtoMessage() {}

func (x *CategoryBrandFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goods_v1_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryBrandFilterRequest.ProtoReflect.Descriptor instead.
func (*CategoryBrandFilterRequest) Descriptor() ([]byte, []int) {
	return file_goods_v1_message_proto_rawDescGZIP(), []int{8}
}

func (x *CategoryBrandFilterRequest) GetPages() int32 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *CategoryBrandFilterRequest) GetPagePerNums() int32 {
	if x != nil {
		return x.PagePerNums
	}
	return 0
}

// 通用过滤请求
type FilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pages         int32                  `protobuf:"varint,1,opt,name=pages,proto3" json:"pages,omitempty"`             // 页码
	PagePerNums   int32                  `protobuf:"varint,2,opt,name=pagePerNums,proto3" json:"pagePerNums,omitempty"` // 每页数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterRequest) Reset() {
	*x = FilterRequest{}
	mi := &file_goods_v1_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterRequest) ProtoMessage() {}

func (x *FilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goods_v1_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterRequest.ProtoReflect.Descriptor instead.
func (*FilterRequest) Descriptor() ([]byte, []int) {
	return file_goods_v1_message_proto_rawDescGZIP(), []int{9}
}

func (x *FilterRequest) GetPages() int32 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *FilterRequest) GetPagePerNums() int32 {
	if x != nil {
		return x.PagePerNums
	}
	return 0
}

// 品牌分类关联请求
type CategoryBrandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                 // 关联ID
	CategoryId    int32                  `protobuf:"varint,2,opt,name=categoryId,proto3" json:"categoryId,omitempty"` // 分类ID
	BrandId       int32                  `protobuf:"varint,3,opt,name=brandId,proto3" json:"brandId,omitempty"`       // 品牌ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryBrandRequest) Reset() {
	*x = CategoryBrandRequest{}
	mi := &file_goods_v1_message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryBrandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryBrandRequest) ProtoMessage() {}

func (x *CategoryBrandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goods_v1_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryBrandRequest.ProtoReflect.Descriptor instead.
func (*CategoryBrandRequest) Descriptor() ([]byte, []int) {
	return file_goods_v1_message_proto_rawDescGZIP(), []int{10}
}

func (x *CategoryBrandRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CategoryBrandRequest) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CategoryBrandRequest) GetBrandId() int32 {
	if x != nil {
		return x.BrandId
	}
	return 0
}

// 品牌分类关联响应
type CategoryBrandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`            // 关联ID
	Brand         *BrandInfoResponse     `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`       // 品牌信息
	Category      *CategoryInfoResponse  `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"` // 分类信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryBrandResponse) Reset() {
	*x = CategoryBrandResponse{}
	mi := &file_goods_v1_message_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryBrandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryBrandResponse) ProtoMessage() {}

func (x *CategoryBrandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goods_v1_message_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryBrandResponse.ProtoReflect.Descriptor instead.
func (*CategoryBrandResponse) Descriptor() ([]byte, []int) {
	return file_goods_v1_message_proto_rawDescGZIP(), []int{11}
}

func (x *CategoryBrandResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CategoryBrandResponse) GetBrand() *BrandInfoResponse {
	if x != nil {
		return x.Brand
	}
	return nil
}

func (x *CategoryBrandResponse) GetCategory() *CategoryInfoResponse {
	if x != nil {
		return x.Category
	}
	return nil
}

// 轮播图请求
type BannerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`       // 轮播图ID
	Index         int32                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"` // 排序索引
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`  // 图片URL
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`      // 跳转链接
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BannerRequest) Reset() {
	*x = BannerRequest{}
	mi := &file_goods_v1_message_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BannerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BannerRequest) ProtoMessage() {}

func (x *BannerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goods_v1_message_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BannerRequest.ProtoReflect.Descriptor instead.
func (*BannerRequest) Descriptor() ([]byte, []int) {
	return file_goods_v1_message_proto_rawDescGZIP(), []int{12}
}

func (x *BannerRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BannerRequest) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *BannerRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *BannerRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// 轮播图响应
type BannerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`       // 轮播图ID
	Index         int32                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"` // 排序索引
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`  // 图片URL
	Url           string                 `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`      // 跳转链接
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BannerResponse) Reset() {
	*x = BannerResponse{}
	mi := &file_goods_v1_message_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BannerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BannerResponse) ProtoMessage() {}

func (x *BannerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goods_v1_message_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BannerResponse.ProtoReflect.Descriptor instead.
func (*BannerResponse) Descriptor() ([]byte, []int) {
	return file_goods_v1_message_proto_rawDescGZIP(), []int{13}
}

func (x *BannerResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BannerResponse) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *BannerResponse) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *BannerResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// 轮播图列表响应
type BannerListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"` // 总数
	Data          []*BannerResponse      `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`    // 轮播图数据列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BannerListResponse) Reset() {
	*x = BannerListResponse{}
	mi := &file_goods_v1_message_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BannerListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BannerListResponse) ProtoMessage() {}

func (x *BannerListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goods_v1_message_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BannerListResponse.ProtoReflect.Descriptor instead.
func (*BannerListResponse) Descriptor() ([]byte, []int) {
	return file_goods_v1_message_proto_rawDescGZIP(), []int{14}
}

func (x *BannerListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *BannerListResponse) GetData() []*BannerResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

// 品牌过滤请求
type BrandFilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pages         int32                  `protobuf:"varint,1,opt,name=pages,proto3" json:"pages,omitempty"`             // 页码
	PagePerNums   int32                  `protobuf:"varint,2,opt,name=pagePerNums,proto3" json:"pagePerNums,omitempty"` // 每页数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrandFilterRequest) Reset() {
	*x = BrandFilterRequest{}
	mi := &file_goods_v1_message_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrandFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrandFilterRequest) ProtoMessage() {}

func (x *BrandFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goods_v1_message_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrandFilterRequest.ProtoReflect.Descriptor instead.
func (*BrandFilterRequest) Descriptor() ([]byte, []int) {
	return file_goods_v1_message_proto_rawDescGZIP(), []int{15}
}

func (x *BrandFilterRequest) GetPages() int32 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *BrandFilterRequest) GetPagePerNums() int32 {
	if x != nil {
		return x.PagePerNums
	}
	return 0
}

// 品牌请求
type BrandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`    // 品牌ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // 品牌名称
	Logo          string                 `protobuf:"bytes,3,opt,name=logo,proto3" json:"logo,omitempty"` // 品牌Logo
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrandRequest) Reset() {
	*x = BrandRequest{}
	mi := &file_goods_v1_message_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrandRequest) ProtoMessage() {}

func (x *BrandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goods_v1_message_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrandRequest.ProtoReflect.Descriptor instead.
func (*BrandRequest) Descriptor() ([]byte, []int) {
	return file_goods_v1_message_proto_rawDescGZIP(), []int{16}
}

func (x *BrandRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BrandRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BrandRequest) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

// 品牌信息响应
type BrandInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`    // 品牌ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // 品牌名称
	Logo          string                 `protobuf:"bytes,3,opt,name=logo,proto3" json:"logo,omitempty"` // 品牌Logo
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrandInfoResponse) Reset() {
	*x = BrandInfoResponse{}
	mi := &file_goods_v1_message_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrandInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrandInfoResponse) ProtoMessage() {}

func (x *BrandInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goods_v1_message_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrandInfoResponse.ProtoReflect.Descriptor instead.
func (*BrandInfoResponse) Descriptor() ([]byte, []int) {
	return file_goods_v1_message_proto_rawDescGZIP(), []int{17}
}

func (x *BrandInfoResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BrandInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BrandInfoResponse) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

// 品牌列表响应
type BrandListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"` // 总数
	Data          []*BrandInfoResponse   `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`    // 品牌数据列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrandListResponse) Reset() {
	*x = BrandListResponse{}
	mi := &file_goods_v1_message_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrandListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrandListResponse) ProtoMessage() {}

func (x *BrandListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goods_v1_message_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrandListResponse.ProtoReflect.Descriptor instead.
func (*BrandListResponse) Descriptor() ([]byte, []int) {
	return file_goods_v1_message_proto_rawDescGZIP(), []int{18}
}

func (x *BrandListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *BrandListResponse) GetData() []*BrandInfoResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

// 品牌分类关联列表响应
type CategoryBrandListResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Total         int32                    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"` // 总数
	Data          []*CategoryBrandResponse `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`    // 品牌分类关联数据列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryBrandListResponse) Reset() {
	*x = CategoryBrandListResponse{}
	mi := &file_goods_v1_message_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryBrandListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryBrandListResponse) ProtoMessage() {}

func (x *CategoryBrandListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goods_v1_message_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryBrandListResponse.ProtoReflect.Descriptor instead.
func (*CategoryBrandListResponse) Descriptor() ([]byte, []int) {
	return file_goods_v1_message_proto_rawDescGZIP(), []int{19}
}

func (x *CategoryBrandListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *CategoryBrandListResponse) GetData() []*CategoryBrandResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

// 批量商品ID信息
type BatchGoodsIdInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []int32                `protobuf:"varint,1,rep,packed,name=id,proto3" json:"id,omitempty"` // 商品ID列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGoodsIdInfo) Reset() {
	*x = BatchGoodsIdInfo{}
	mi := &file_goods_v1_message_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGoodsIdInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGoodsIdInfo) ProtoMessage() {}

func (x *BatchGoodsIdInfo) ProtoReflect() protoreflect.Message {
	mi := &file_goods_v1_message_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGoodsIdInfo.ProtoReflect.Descriptor instead.
func (*BatchGoodsIdInfo) Descriptor() ([]byte, []int) {
	return file_goods_v1_message_proto_rawDescGZIP(), []int{20}
}

func (x *BatchGoodsIdInfo) GetId() []int32 {
	if x != nil {
		return x.Id
	}
	return nil
}

// 删除商品信息
type DeleteGoodsInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 要删除的商品ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGoodsInfo) Reset() {
	*x = DeleteGoodsInfo{}
	mi := &file_goods_v1_message_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGoodsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGoodsInfo) ProtoMessage() {}

func (x *DeleteGoodsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_goods_v1_message_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGoodsInfo.ProtoReflect.Descriptor instead.
func (*DeleteGoodsInfo) Descriptor() ([]byte, []int) {
	return file_goods_v1_message_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteGoodsInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 分类简要信息响应
type CategoryBriefInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`    // 分类ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // 分类名称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryBriefInfoResponse) Reset() {
	*x = CategoryBriefInfoResponse{}
	mi := &file_goods_v1_message_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryBriefInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryBriefInfoResponse) ProtoMessage() {}

func (x *CategoryBriefInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goods_v1_message_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryBriefInfoResponse.ProtoReflect.Descriptor instead.
func (*CategoryBriefInfoResponse) Descriptor() ([]byte, []int) {
	return file_goods_v1_message_proto_rawDescGZIP(), []int{22}
}

func (x *CategoryBriefInfoResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CategoryBriefInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 分类过滤请求
type CategoryFilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`       // 分类ID
	IsTab         bool                   `protobuf:"varint,2,opt,name=isTab,proto3" json:"isTab,omitempty"` // 是否为标签页
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryFilterRequest) Reset() {
	*x = CategoryFilterRequest{}
	mi := &file_goods_v1_message_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryFilterRequest) ProtoMessage() {}

func (x *CategoryFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goods_v1_message_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryFilterRequest.ProtoReflect.Descriptor instead.
func (*CategoryFilterRequest) Descriptor() ([]byte, []int) {
	return file_goods_v1_message_proto_rawDescGZIP(), []int{23}
}

func (x *CategoryFilterRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CategoryFilterRequest) GetIsTab() bool {
	if x != nil {
		return x.IsTab
	}
	return false
}

// 商品信息请求
type GoodInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 商品ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodInfoRequest) Reset() {
	*x = GoodInfoRequest{}
	mi := &file_goods_v1_message_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodInfoRequest) ProtoMessage() {}

func (x *GoodInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goods_v1_message_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodInfoRequest.ProtoReflect.Descriptor instead.
func (*GoodInfoRequest) Descriptor() ([]byte, []int) {
	return file_goods_v1_message_proto_rawDescGZIP(), []int{24}
}

func (x *GoodInfoRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// 创建商品信息
type CreateGoodsInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                           // 商品ID
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                        // 商品名称
	GoodsSn         string                 `protobuf:"bytes,3,opt,name=goodsSn,proto3" json:"goodsSn,omitempty"`                  // 商品编号
	Stocks          int32                  `protobuf:"varint,7,opt,name=stocks,proto3" json:"stocks,omitempty"`                   // 库存数量
	MarketPrice     float32                `protobuf:"fixed32,8,opt,name=marketPrice,proto3" json:"marketPrice,omitempty"`        // 市场价格
	ShopPrice       float32                `protobuf:"fixed32,9,opt,name=shopPrice,proto3" json:"shopPrice,omitempty"`            // 店铺价格
	GoodsBrief      string                 `protobuf:"bytes,10,opt,name=goodsBrief,proto3" json:"goodsBrief,omitempty"`           // 商品简介
	GoodsDesc       string                 `protobuf:"bytes,11,opt,name=goodsDesc,proto3" json:"goodsDesc,omitempty"`             // 商品描述
	ShipFree        bool                   `protobuf:"varint,12,opt,name=shipFree,proto3" json:"shipFree,omitempty"`              // 是否包邮
	Images          []string               `protobuf:"bytes,13,rep,name=images,proto3" json:"images,omitempty"`                   // 商品图片列表
	DescImages      []string               `protobuf:"bytes,14,rep,name=descImages,proto3" json:"descImages,omitempty"`           // 商品描述图片列表
	GoodsFrontImage string                 `protobuf:"bytes,15,opt,name=goodsFrontImage,proto3" json:"goodsFrontImage,omitempty"` // 商品主图
	IsNew           bool                   `protobuf:"varint,16,opt,name=isNew,proto3" json:"isNew,omitempty"`                    // 是否新品
	IsHot           bool                   `protobuf:"varint,17,opt,name=isHot,proto3" json:"isHot,omitempty"`                    // 是否热销
	OnSale          bool                   `protobuf:"varint,18,opt,name=onSale,proto3" json:"onSale,omitempty"`                  // 是否上架
	CategoryId      int32                  `protobuf:"varint,19,opt,name=categoryId,proto3" json:"categoryId,omitempty"`          // 分类ID
	BrandId         int32                  `protobuf:"varint,20,opt,name=brandId,proto3" json:"brandId,omitempty"`                // 品牌ID
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateGoodsInfo) Reset() {
	*x = CreateGoodsInfo{}
	mi := &file_goods_v1_message_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGoodsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGoodsInfo) ProtoMessage() {}

func (x *CreateGoodsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_goods_v1_message_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGoodsInfo.ProtoReflect.Descriptor instead.
func (*CreateGoodsInfo) Descriptor() ([]byte, []int) {
	return file_goods_v1_message_proto_rawDescGZIP(), []int{25}
}

func (x *CreateGoodsInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateGoodsInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGoodsInfo) GetGoodsSn() string {
	if x != nil {
		return x.GoodsSn
	}
	return ""
}

func (x *CreateGoodsInfo) GetStocks() int32 {
	if x != nil {
		return x.Stocks
	}
	return 0
}

func (x *CreateGoodsInfo) GetMarketPrice() float32 {
	if x != nil {
		return x.MarketPrice
	}
	return 0
}

func (x *CreateGoodsInfo) GetShopPrice() float32 {
	if x != nil {
		return x.ShopPrice
	}
	return 0
}

func (x *CreateGoodsInfo) GetGoodsBrief() string {
	if x != nil {
		return x.GoodsBrief
	}
	return ""
}

func (x *CreateGoodsInfo) GetGoodsDesc() string {
	if x != nil {
		return x.GoodsDesc
	}
	return ""
}

func (x *CreateGoodsInfo) GetShipFree() bool {
	if x != nil {
		return x.ShipFree
	}
	return false
}

func (x *CreateGoodsInfo) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *CreateGoodsInfo) GetDescImages() []string {
	if x != nil {
		return x.DescImages
	}
	return nil
}

func (x *CreateGoodsInfo) GetGoodsFrontImage() string {
	if x != nil {
		return x.GoodsFrontImage
	}
	return ""
}

func (x *CreateGoodsInfo) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

func (x *CreateGoodsInfo) GetIsHot() bool {
	if x != nil {
		return x.IsHot
	}
	return false
}

func (x *CreateGoodsInfo) GetOnSale() bool {
	if x != nil {
		return x.OnSale
	}
	return false
}

func (x *CreateGoodsInfo) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CreateGoodsInfo) GetBrandId() int32 {
	if x != nil {
		return x.BrandId
	}
	return 0
}

// 商品减库存请求
type GoodsReduceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GoodsId       int32                  `protobuf:"varint,1,opt,name=GoodsId,proto3" json:"GoodsId,omitempty"` // 商品ID
	Nums          int32                  `protobuf:"varint,2,opt,name=nums,proto3" json:"nums,omitempty"`       // 减少数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsReduceRequest) Reset() {
	*x = GoodsReduceRequest{}
	mi := &file_goods_v1_message_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsReduceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsReduceRequest) ProtoMessage() {}

func (x *GoodsReduceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goods_v1_message_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsReduceRequest.ProtoReflect.Descriptor instead.
func (*GoodsReduceRequest) Descriptor() ([]byte, []int) {
	return file_goods_v1_message_proto_rawDescGZIP(), []int{26}
}

func (x *GoodsReduceRequest) GetGoodsId() int32 {
	if x != nil {
		return x.GoodsId
	}
	return 0
}

func (x *GoodsReduceRequest) GetNums() int32 {
	if x != nil {
		return x.Nums
	}
	return 0
}

// 批量分类信息请求
type BatchCategoryInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []int32                `protobuf:"varint,1,rep,packed,name=id,proto3" json:"id,omitempty"`        // 分类ID列表
	GoodsNums     int32                  `protobuf:"varint,2,opt,name=goodsNums,proto3" json:"goodsNums,omitempty"` // 商品数量
	BrandNums     int32                  `protobuf:"varint,3,opt,name=brandNums,proto3" json:"brandNums,omitempty"` // 品牌数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCategoryInfoRequest) Reset() {
	*x = BatchCategoryInfoRequest{}
	mi := &file_goods_v1_message_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCategoryInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCategoryInfoRequest) ProtoMessage() {}

func (x *BatchCategoryInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goods_v1_message_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCategoryInfoRequest.ProtoReflect.Descriptor instead.
func (*BatchCategoryInfoRequest) Descriptor() ([]byte, []int) {
	return file_goods_v1_message_proto_rawDescGZIP(), []int{27}
}

func (x *BatchCategoryInfoRequest) GetId() []int32 {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *BatchCategoryInfoRequest) GetGoodsNums() int32 {
	if x != nil {
		return x.GoodsNums
	}
	return 0
}

func (x *BatchCategoryInfoRequest) GetBrandNums() int32 {
	if x != nil {
		return x.BrandNums
	}
	return 0
}

// 商品过滤请求
type GoodsFilterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PriceMin      int32                  `protobuf:"varint,1,opt,name=priceMin,proto3" json:"priceMin,omitempty"`       // 最低价格
	PriceMax      int32                  `protobuf:"varint,2,opt,name=priceMax,proto3" json:"priceMax,omitempty"`       // 最高价格
	IsHot         bool                   `protobuf:"varint,3,opt,name=isHot,proto3" json:"isHot,omitempty"`             // 是否热销
	IsNew         bool                   `protobuf:"varint,4,opt,name=isNew,proto3" json:"isNew,omitempty"`             // 是否新品
	IsTab         bool                   `protobuf:"varint,5,opt,name=isTab,proto3" json:"isTab,omitempty"`             // 是否为标签页
	TopCategory   int32                  `protobuf:"varint,6,opt,name=topCategory,proto3" json:"topCategory,omitempty"` // 顶级分类
	Pages         int32                  `protobuf:"varint,7,opt,name=pages,proto3" json:"pages,omitempty"`             // 页码
	PagePerNums   int32                  `protobuf:"varint,8,opt,name=pagePerNums,proto3" json:"pagePerNums,omitempty"` // 每页数量
	KeyWords      string                 `protobuf:"bytes,9,opt,name=keyWords,proto3" json:"keyWords,omitempty"`        // 关键词
	Brand         int32                  `protobuf:"varint,10,opt,name=brand,proto3" json:"brand,omitempty"`            // 品牌ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsFilterRequest) Reset() {
	*x = GoodsFilterRequest{}
	mi := &file_goods_v1_message_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsFilterRequest) ProtoMessage() {}

func (x *GoodsFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_goods_v1_message_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsFilterRequest.ProtoReflect.Descriptor instead.
func (*GoodsFilterRequest) Descriptor() ([]byte, []int) {
	return file_goods_v1_message_proto_rawDescGZIP(), []int{28}
}

func (x *GoodsFilterRequest) GetPriceMin() int32 {
	if x != nil {
		return x.PriceMin
	}
	return 0
}

func (x *GoodsFilterRequest) GetPriceMax() int32 {
	if x != nil {
		return x.PriceMax
	}
	return 0
}

func (x *GoodsFilterRequest) GetIsHot() bool {
	if x != nil {
		return x.IsHot
	}
	return false
}

func (x *GoodsFilterRequest) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

func (x *GoodsFilterRequest) GetIsTab() bool {
	if x != nil {
		return x.IsTab
	}
	return false
}

func (x *GoodsFilterRequest) GetTopCategory() int32 {
	if x != nil {
		return x.TopCategory
	}
	return 0
}

func (x *GoodsFilterRequest) GetPages() int32 {
	if x != nil {
		return x.Pages
	}
	return 0
}

func (x *GoodsFilterRequest) GetPagePerNums() int32 {
	if x != nil {
		return x.PagePerNums
	}
	return 0
}

func (x *GoodsFilterRequest) GetKeyWords() string {
	if x != nil {
		return x.KeyWords
	}
	return ""
}

func (x *GoodsFilterRequest) GetBrand() int32 {
	if x != nil {
		return x.Brand
	}
	return 0
}

// 商品信息响应
type GoodsInfoResponse struct {
	state           protoimpl.MessageState     `protogen:"open.v1"`
	Id              int32                      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                           // 商品ID
	CategoryId      int32                      `protobuf:"varint,2,opt,name=categoryId,proto3" json:"categoryId,omitempty"`           // 分类ID
	Name            string                     `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                        // 商品名称
	GoodsSn         string                     `protobuf:"bytes,4,opt,name=goodsSn,proto3" json:"goodsSn,omitempty"`                  // 商品编号
	ClickNum        int32                      `protobuf:"varint,5,opt,name=clickNum,proto3" json:"clickNum,omitempty"`               // 点击数量
	SoldNum         int32                      `protobuf:"varint,6,opt,name=soldNum,proto3" json:"soldNum,omitempty"`                 // 销售数量
	FavNum          int32                      `protobuf:"varint,7,opt,name=favNum,proto3" json:"favNum,omitempty"`                   // 收藏数量
	MarketPrice     float32                    `protobuf:"fixed32,9,opt,name=marketPrice,proto3" json:"marketPrice,omitempty"`        // 市场价格
	ShopPrice       float32                    `protobuf:"fixed32,10,opt,name=shopPrice,proto3" json:"shopPrice,omitempty"`           // 店铺价格
	GoodsBrief      string                     `protobuf:"bytes,11,opt,name=goodsBrief,proto3" json:"goodsBrief,omitempty"`           // 商品简介
	GoodsDesc       string                     `protobuf:"bytes,12,opt,name=goodsDesc,proto3" json:"goodsDesc,omitempty"`             // 商品描述
	ShipFree        bool                       `protobuf:"varint,13,opt,name=shipFree,proto3" json:"shipFree,omitempty"`              // 是否包邮
	Images          []string                   `protobuf:"bytes,14,rep,name=images,proto3" json:"images,omitempty"`                   // 商品图片列表
	DescImages      []string                   `protobuf:"bytes,15,rep,name=descImages,proto3" json:"descImages,omitempty"`           // 商品描述图片列表
	GoodsFrontImage string                     `protobuf:"bytes,16,opt,name=goodsFrontImage,proto3" json:"goodsFrontImage,omitempty"` // 商品主图
	IsNew           bool                       `protobuf:"varint,17,opt,name=isNew,proto3" json:"isNew,omitempty"`                    // 是否新品
	IsHot           bool                       `protobuf:"varint,18,opt,name=isHot,proto3" json:"isHot,omitempty"`                    // 是否热销
	OnSale          bool                       `protobuf:"varint,19,opt,name=onSale,proto3" json:"onSale,omitempty"`                  // 是否上架
	AddTime         int64                      `protobuf:"varint,20,opt,name=addTime,proto3" json:"addTime,omitempty"`                // 添加时间
	Category        *CategoryBriefInfoResponse `protobuf:"bytes,21,opt,name=category,proto3" json:"category,omitempty"`               // 分类信息
	Brand           *BrandInfoResponse         `protobuf:"bytes,22,opt,name=brand,proto3" json:"brand,omitempty"`                     // 品牌信息
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GoodsInfoResponse) Reset() {
	*x = GoodsInfoResponse{}
	mi := &file_goods_v1_message_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsInfoResponse) ProtoMessage() {}

func (x *GoodsInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goods_v1_message_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsInfoResponse.ProtoReflect.Descriptor instead.
func (*GoodsInfoResponse) Descriptor() ([]byte, []int) {
	return file_goods_v1_message_proto_rawDescGZIP(), []int{29}
}

func (x *GoodsInfoResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GoodsInfoResponse) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *GoodsInfoResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GoodsInfoResponse) GetGoodsSn() string {
	if x != nil {
		return x.GoodsSn
	}
	return ""
}

func (x *GoodsInfoResponse) GetClickNum() int32 {
	if x != nil {
		return x.ClickNum
	}
	return 0
}

func (x *GoodsInfoResponse) GetSoldNum() int32 {
	if x != nil {
		return x.SoldNum
	}
	return 0
}

func (x *GoodsInfoResponse) GetFavNum() int32 {
	if x != nil {
		return x.FavNum
	}
	return 0
}

func (x *GoodsInfoResponse) GetMarketPrice() float32 {
	if x != nil {
		return x.MarketPrice
	}
	return 0
}

func (x *GoodsInfoResponse) GetShopPrice() float32 {
	if x != nil {
		return x.ShopPrice
	}
	return 0
}

func (x *GoodsInfoResponse) GetGoodsBrief() string {
	if x != nil {
		return x.GoodsBrief
	}
	return ""
}

func (x *GoodsInfoResponse) GetGoodsDesc() string {
	if x != nil {
		return x.GoodsDesc
	}
	return ""
}

func (x *GoodsInfoResponse) GetShipFree() bool {
	if x != nil {
		return x.ShipFree
	}
	return false
}

func (x *GoodsInfoResponse) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *GoodsInfoResponse) GetDescImages() []string {
	if x != nil {
		return x.DescImages
	}
	return nil
}

func (x *GoodsInfoResponse) GetGoodsFrontImage() string {
	if x != nil {
		return x.GoodsFrontImage
	}
	return ""
}

func (x *GoodsInfoResponse) GetIsNew() bool {
	if x != nil {
		return x.IsNew
	}
	return false
}

func (x *GoodsInfoResponse) GetIsHot() bool {
	if x != nil {
		return x.IsHot
	}
	return false
}

func (x *GoodsInfoResponse) GetOnSale() bool {
	if x != nil {
		return x.OnSale
	}
	return false
}

func (x *GoodsInfoResponse) GetAddTime() int64 {
	if x != nil {
		return x.AddTime
	}
	return 0
}

func (x *GoodsInfoResponse) GetCategory() *CategoryBriefInfoResponse {
	if x != nil {
		return x.Category
	}
	return nil
}

func (x *GoodsInfoResponse) GetBrand() *BrandInfoResponse {
	if x != nil {
		return x.Brand
	}
	return nil
}

// 商品列表响应
type GoodsListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"` // 总数
	Data          []*GoodsInfoResponse   `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`    // 商品数据列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GoodsListResponse) Reset() {
	*x = GoodsListResponse{}
	mi := &file_goods_v1_message_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GoodsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GoodsListResponse) ProtoMessage() {}

func (x *GoodsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_goods_v1_message_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GoodsListResponse.ProtoReflect.Descriptor instead.
func (*GoodsListResponse) Descriptor() ([]byte, []int) {
	return file_goods_v1_message_proto_rawDescGZIP(), []int{30}
}

func (x *GoodsListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GoodsListResponse) GetData() []*GoodsInfoResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_goods_v1_message_proto protoreflect.FileDescriptor

const file_goods_v1_message_proto_rawDesc = "" +
	"\n" +
	"\x16goods/v1/message.proto\x12\x1aservice.goods.api.goods.v1\"\a\n" +
	"\x05Empty\";\n" +
	"\x13CategoryListRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\"\x8d\x01\n" +
	"\x13CategoryInfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12&\n" +
	"\x0eparentCategory\x18\x03 \x01(\x05R\x0eparentCategory\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12\x14\n" +
	"\x05isTab\x18\x05 \x01(\bR\x05isTab\"'\n" +
	"\x15DeleteCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\":\n" +
	"\x14QueryCategoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x8e\x01\n" +
	"\x14CategoryInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12&\n" +
	"\x0eparentCategory\x18\x03 \x01(\x05R\x0eparentCategory\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12\x14\n" +
	"\x05isTab\x18\x05 \x01(\bR\x05isTab\"\x8e\x01\n" +
	"\x14CategoryListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12D\n" +
	"\x04data\x18\x02 \x03(\v20.service.goods.api.goods.v1.CategoryInfoResponseR\x04data\x12\x1a\n" +
	"\bjsonData\x18\x03 \x01(\tR\bjsonData\"\xcb\x01\n" +
	"\x17SubCategoryListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12D\n" +
	"\x04info\x18\x02 \x01(\v20.service.goods.api.goods.v1.CategoryInfoResponseR\x04info\x12T\n" +
	"\fsubCategorys\x18\x03 \x03(\v20.service.goods.api.goods.v1.CategoryInfoResponseR\fsubCategorys\"T\n" +
	"\x1aCategoryBrandFilterRequest\x12\x14\n" +
	"\x05pages\x18\x01 \x01(\x05R\x05pages\x12 \n" +
	"\vpagePerNums\x18\x02 \x01(\x05R\vpagePerNums\"G\n" +
	"\rFilterRequest\x12\x14\n" +
	"\x05pages\x18\x01 \x01(\x05R\x05pages\x12 \n" +
	"\vpagePerNums\x18\x02 \x01(\x05R\vpagePerNums\"`\n" +
	"\x14CategoryBrandRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1e\n" +
	"\n" +
	"categoryId\x18\x02 \x01(\x05R\n" +
	"categoryId\x12\x18\n" +
	"\abrandId\x18\x03 \x01(\x05R\abrandId\"\xba\x01\n" +
	"\x15CategoryBrandResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12C\n" +
	"\x05brand\x18\x02 \x01(\v2-.service.goods.api.goods.v1.BrandInfoResponseR\x05brand\x12L\n" +
	"\bcategory\x18\x03 \x01(\v20.service.goods.api.goods.v1.CategoryInfoResponseR\bcategory\"]\n" +
	"\rBannerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x05R\x05index\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\"^\n" +
	"\x0eBannerResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x05R\x05index\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\"j\n" +
	"\x12BannerListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12>\n" +
	"\x04data\x18\x02 \x03(\v2*.service.goods.api.goods.v1.BannerResponseR\x04data\"L\n" +
	"\x12BrandFilterRequest\x12\x14\n" +
	"\x05pages\x18\x01 \x01(\x05R\x05pages\x12 \n" +
	"\vpagePerNums\x18\x02 \x01(\x05R\vpagePerNums\"F\n" +
	"\fBrandRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04logo\x18\x03 \x01(\tR\x04logo\"K\n" +
	"\x11BrandInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04logo\x18\x03 \x01(\tR\x04logo\"l\n" +
	"\x11BrandListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12A\n" +
	"\x04data\x18\x02 \x03(\v2-.service.goods.api.goods.v1.BrandInfoResponseR\x04data\"x\n" +
	"\x19CategoryBrandListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12E\n" +
	"\x04data\x18\x02 \x03(\v21.service.goods.api.goods.v1.CategoryBrandResponseR\x04data\"\"\n" +
	"\x10BatchGoodsIdInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x03(\x05R\x02id\"!\n" +
	"\x0fDeleteGoodsInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"?\n" +
	"\x19CategoryBriefInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"=\n" +
	"\x15CategoryFilterRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05isTab\x18\x02 \x01(\bR\x05isTab\"!\n" +
	"\x0fGoodInfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\xe1\x03\n" +
	"\x0fCreateGoodsInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\agoodsSn\x18\x03 \x01(\tR\agoodsSn\x12\x16\n" +
	"\x06stocks\x18\a \x01(\x05R\x06stocks\x12 \n" +
	"\vmarketPrice\x18\b \x01(\x02R\vmarketPrice\x12\x1c\n" +
	"\tshopPrice\x18\t \x01(\x02R\tshopPrice\x12\x1e\n" +
	"\n" +
	"goodsBrief\x18\n" +
	" \x01(\tR\n" +
	"goodsBrief\x12\x1c\n" +
	"\tgoodsDesc\x18\v \x01(\tR\tgoodsDesc\x12\x1a\n" +
	"\bshipFree\x18\f \x01(\bR\bshipFree\x12\x16\n" +
	"\x06images\x18\r \x03(\tR\x06images\x12\x1e\n" +
	"\n" +
	"descImages\x18\x0e \x03(\tR\n" +
	"descImages\x12(\n" +
	"\x0fgoodsFrontImage\x18\x0f \x01(\tR\x0fgoodsFrontImage\x12\x14\n" +
	"\x05isNew\x18\x10 \x01(\bR\x05isNew\x12\x14\n" +
	"\x05isHot\x18\x11 \x01(\bR\x05isHot\x12\x16\n" +
	"\x06onSale\x18\x12 \x01(\bR\x06onSale\x12\x1e\n" +
	"\n" +
	"categoryId\x18\x13 \x01(\x05R\n" +
	"categoryId\x12\x18\n" +
	"\abrandId\x18\x14 \x01(\x05R\abrandId\"B\n" +
	"\x12GoodsReduceRequest\x12\x18\n" +
	"\aGoodsId\x18\x01 \x01(\x05R\aGoodsId\x12\x12\n" +
	"\x04nums\x18\x02 \x01(\x05R\x04nums\"f\n" +
	"\x18BatchCategoryInfoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x03(\x05R\x02id\x12\x1c\n" +
	"\tgoodsNums\x18\x02 \x01(\x05R\tgoodsNums\x12\x1c\n" +
	"\tbrandNums\x18\x03 \x01(\x05R\tbrandNums\"\x9a\x02\n" +
	"\x12GoodsFilterRequest\x12\x1a\n" +
	"\bpriceMin\x18\x01 \x01(\x05R\bpriceMin\x12\x1a\n" +
	"\bpriceMax\x18\x02 \x01(\x05R\bpriceMax\x12\x14\n" +
	"\x05isHot\x18\x03 \x01(\bR\x05isHot\x12\x14\n" +
	"\x05isNew\x18\x04 \x01(\bR\x05isNew\x12\x14\n" +
	"\x05isTab\x18\x05 \x01(\bR\x05isTab\x12 \n" +
	"\vtopCategory\x18\x06 \x01(\x05R\vtopCategory\x12\x14\n" +
	"\x05pages\x18\a \x01(\x05R\x05pages\x12 \n" +
	"\vpagePerNums\x18\b \x01(\x05R\vpagePerNums\x12\x1a\n" +
	"\bkeyWords\x18\t \x01(\tR\bkeyWords\x12\x14\n" +
	"\x05brand\x18\n" +
	" \x01(\x05R\x05brand\"\xb1\x05\n" +
	"\x11GoodsInfoResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1e\n" +
	"\n" +
	"categoryId\x18\x02 \x01(\x05R\n" +
	"categoryId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\agoodsSn\x18\x04 \x01(\tR\agoodsSn\x12\x1a\n" +
	"\bclickNum\x18\x05 \x01(\x05R\bclickNum\x12\x18\n" +
	"\asoldNum\x18\x06 \x01(\x05R\asoldNum\x12\x16\n" +
	"\x06favNum\x18\a \x01(\x05R\x06favNum\x12 \n" +
	"\vmarketPrice\x18\t \x01(\x02R\vmarketPrice\x12\x1c\n" +
	"\tshopPrice\x18\n" +
	" \x01(\x02R\tshopPrice\x12\x1e\n" +
	"\n" +
	"goodsBrief\x18\v \x01(\tR\n" +
	"goodsBrief\x12\x1c\n" +
	"\tgoodsDesc\x18\f \x01(\tR\tgoodsDesc\x12\x1a\n" +
	"\bshipFree\x18\r \x01(\bR\bshipFree\x12\x16\n" +
	"\x06images\x18\x0e \x03(\tR\x06images\x12\x1e\n" +
	"\n" +
	"descImages\x18\x0f \x03(\tR\n" +
	"descImages\x12(\n" +
	"\x0fgoodsFrontImage\x18\x10 \x01(\tR\x0fgoodsFrontImage\x12\x14\n" +
	"\x05isNew\x18\x11 \x01(\bR\x05isNew\x12\x14\n" +
	"\x05isHot\x18\x12 \x01(\bR\x05isHot\x12\x16\n" +
	"\x06onSale\x18\x13 \x01(\bR\x06onSale\x12\x18\n" +
	"\aaddTime\x18\x14 \x01(\x03R\aaddTime\x12Q\n" +
	"\bcategory\x18\x15 \x01(\v25.service.goods.api.goods.v1.CategoryBriefInfoResponseR\bcategory\x12C\n" +
	"\x05brand\x18\x16 \x01(\v2-.service.goods.api.goods.v1.BrandInfoResponseR\x05brand\"l\n" +
	"\x11GoodsListResponse\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12A\n" +
	"\x04data\x18\x02 \x03(\v2-.service.goods.api.goods.v1.GoodsInfoResponseR\x04dataBC\n" +
	"\x1aservice.goods.api.goods.v1P\x01Z#mshop/service/goods/api/goods/v1;v1b\x06proto3"

var (
	file_goods_v1_message_proto_rawDescOnce sync.Once
	file_goods_v1_message_proto_rawDescData []byte
)

func file_goods_v1_message_proto_rawDescGZIP() []byte {
	file_goods_v1_message_proto_rawDescOnce.Do(func() {
		file_goods_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_goods_v1_message_proto_rawDesc), len(file_goods_v1_message_proto_rawDesc)))
	})
	return file_goods_v1_message_proto_rawDescData
}

var file_goods_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_goods_v1_message_proto_goTypes = []any{
	(*Empty)(nil),                      // 0: service.goods.api.goods.v1.Empty
	(*CategoryListRequest)(nil),        // 1: service.goods.api.goods.v1.CategoryListRequest
	(*CategoryInfoRequest)(nil),        // 2: service.goods.api.goods.v1.CategoryInfoRequest
	(*DeleteCategoryRequest)(nil),      // 3: service.goods.api.goods.v1.DeleteCategoryRequest
	(*QueryCategoryRequest)(nil),       // 4: service.goods.api.goods.v1.QueryCategoryRequest
	(*CategoryInfoResponse)(nil),       // 5: service.goods.api.goods.v1.CategoryInfoResponse
	(*CategoryListResponse)(nil),       // 6: service.goods.api.goods.v1.CategoryListResponse
	(*SubCategoryListResponse)(nil),    // 7: service.goods.api.goods.v1.SubCategoryListResponse
	(*CategoryBrandFilterRequest)(nil), // 8: service.goods.api.goods.v1.CategoryBrandFilterRequest
	(*FilterRequest)(nil),              // 9: service.goods.api.goods.v1.FilterRequest
	(*CategoryBrandRequest)(nil),       // 10: service.goods.api.goods.v1.CategoryBrandRequest
	(*CategoryBrandResponse)(nil),      // 11: service.goods.api.goods.v1.CategoryBrandResponse
	(*BannerRequest)(nil),              // 12: service.goods.api.goods.v1.BannerRequest
	(*BannerResponse)(nil),             // 13: service.goods.api.goods.v1.BannerResponse
	(*BannerListResponse)(nil),         // 14: service.goods.api.goods.v1.BannerListResponse
	(*BrandFilterRequest)(nil),         // 15: service.goods.api.goods.v1.BrandFilterRequest
	(*BrandRequest)(nil),               // 16: service.goods.api.goods.v1.BrandRequest
	(*BrandInfoResponse)(nil),          // 17: service.goods.api.goods.v1.BrandInfoResponse
	(*BrandListResponse)(nil),          // 18: service.goods.api.goods.v1.BrandListResponse
	(*CategoryBrandListResponse)(nil),  // 19: service.goods.api.goods.v1.CategoryBrandListResponse
	(*BatchGoodsIdInfo)(nil),           // 20: service.goods.api.goods.v1.BatchGoodsIdInfo
	(*DeleteGoodsInfo)(nil),            // 21: service.goods.api.goods.v1.DeleteGoodsInfo
	(*CategoryBriefInfoResponse)(nil),  // 22: service.goods.api.goods.v1.CategoryBriefInfoResponse
	(*CategoryFilterRequest)(nil),      // 23: service.goods.api.goods.v1.CategoryFilterRequest
	(*GoodInfoRequest)(nil),            // 24: service.goods.api.goods.v1.GoodInfoRequest
	(*CreateGoodsInfo)(nil),            // 25: service.goods.api.goods.v1.CreateGoodsInfo
	(*GoodsReduceRequest)(nil),         // 26: service.goods.api.goods.v1.GoodsReduceRequest
	(*BatchCategoryInfoRequest)(nil),   // 27: service.goods.api.goods.v1.BatchCategoryInfoRequest
	(*GoodsFilterRequest)(nil),         // 28: service.goods.api.goods.v1.GoodsFilterRequest
	(*GoodsInfoResponse)(nil),          // 29: service.goods.api.goods.v1.GoodsInfoResponse
	(*GoodsListResponse)(nil),          // 30: service.goods.api.goods.v1.GoodsListResponse
}
var file_goods_v1_message_proto_depIdxs = []int32{
	5,  // 0: service.goods.api.goods.v1.CategoryListResponse.data:type_name -> service.goods.api.goods.v1.CategoryInfoResponse
	5,  // 1: service.goods.api.goods.v1.SubCategoryListResponse.info:type_name -> service.goods.api.goods.v1.CategoryInfoResponse
	5,  // 2: service.goods.api.goods.v1.SubCategoryListResponse.subCategorys:type_name -> service.goods.api.goods.v1.CategoryInfoResponse
	17, // 3: service.goods.api.goods.v1.CategoryBrandResponse.brand:type_name -> service.goods.api.goods.v1.BrandInfoResponse
	5,  // 4: service.goods.api.goods.v1.CategoryBrandResponse.category:type_name -> service.goods.api.goods.v1.CategoryInfoResponse
	13, // 5: service.goods.api.goods.v1.BannerListResponse.data:type_name -> service.goods.api.goods.v1.BannerResponse
	17, // 6: service.goods.api.goods.v1.BrandListResponse.data:type_name -> service.goods.api.goods.v1.BrandInfoResponse
	11, // 7: service.goods.api.goods.v1.CategoryBrandListResponse.data:type_name -> service.goods.api.goods.v1.CategoryBrandResponse
	22, // 8: service.goods.api.goods.v1.GoodsInfoResponse.category:type_name -> service.goods.api.goods.v1.CategoryBriefInfoResponse
	17, // 9: service.goods.api.goods.v1.GoodsInfoResponse.brand:type_name -> service.goods.api.goods.v1.BrandInfoResponse
	29, // 10: service.goods.api.goods.v1.GoodsListResponse.data:type_name -> service.goods.api.goods.v1.GoodsInfoResponse
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_goods_v1_message_proto_init() }
func file_goods_v1_message_proto_init() {
	if File_goods_v1_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_goods_v1_message_proto_rawDesc), len(file_goods_v1_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_goods_v1_message_proto_goTypes,
		DependencyIndexes: file_goods_v1_message_proto_depIdxs,
		MessageInfos:      file_goods_v1_message_proto_msgTypes,
	}.Build()
	File_goods_v1_message_proto = out.File
	file_goods_v1_message_proto_goTypes = nil
	file_goods_v1_message_proto_depIdxs = nil
}
