// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.11
// source: goods/v1/service.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_goods_v1_service_proto protoreflect.FileDescriptor

const file_goods_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x16goods/v1/service.proto\x12\x1aservice.goods.api.goods.v1\x1a\x16goods/v1/message.proto\x1a\x1cgoogle/api/annotations.proto2\x98\x19\n" +
	"\x05Goods\x12}\n" +
	"\tGoodsList\x12..service.goods.api.goods.v1.GoodsFilterRequest\x1a-.service.goods.api.goods.v1.GoodsListResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/goods\x12\x88\x01\n" +
	"\rBatchGetGoods\x12,.service.goods.api.goods.v1.BatchGoodsIdInfo\x1a-.service.goods.api.goods.v1.GoodsListResponse\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\"\x0f/v1/goods/batch\x12\x7f\n" +
	"\vCreateGoods\x12+.service.goods.api.goods.v1.CreateGoodsInfo\x1a-.service.goods.api.goods.v1.GoodsInfoResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/goods\x12u\n" +
	"\vDeleteGoods\x12+.service.goods.api.goods.v1.DeleteGoodsInfo\x1a!.service.goods.api.goods.v1.Empty\"\x16\x82\xd3\xe4\x93\x02\x10*\x0e/v1/goods/{id}\x12x\n" +
	"\vUpdateGoods\x12+.service.goods.api.goods.v1.CreateGoodsInfo\x1a!.service.goods.api.goods.v1.Empty\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\x1a\x0e/v1/goods/{id}\x12\x84\x01\n" +
	"\x0eGetGoodsDetail\x12+.service.goods.api.goods.v1.GoodInfoRequest\x1a-.service.goods.api.goods.v1.GoodsInfoResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/goods/{id}\x12\x82\x01\n" +
	"\x13GetAllCategorysList\x12!.service.goods.api.goods.v1.Empty\x1a0.service.goods.api.goods.v1.CategoryListResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/categories\x12\x97\x01\n" +
	"\x0eGetSubCategory\x12/.service.goods.api.goods.v1.CategoryListRequest\x1a3.service.goods.api.goods.v1.SubCategoryListResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/categories/{id}/sub\x12\x8e\x01\n" +
	"\x0eCreateCategory\x12/.service.goods.api.goods.v1.CategoryInfoRequest\x1a0.service.goods.api.goods.v1.CategoryInfoResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/categories\x12\x83\x01\n" +
	"\x0eDeleteCategory\x121.service.goods.api.goods.v1.DeleteCategoryRequest\x1a!.service.goods.api.goods.v1.Empty\"\x1b\x82\xd3\xe4\x93\x02\x15*\x13/v1/categories/{id}\x12\x84\x01\n" +
	"\x0eUpdateCategory\x12/.service.goods.api.goods.v1.CategoryInfoRequest\x1a!.service.goods.api.goods.v1.Empty\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\x1a\x13/v1/categories/{id}\x12~\n" +
	"\tBrandList\x12..service.goods.api.goods.v1.BrandFilterRequest\x1a-.service.goods.api.goods.v1.BrandListResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/brands\x12}\n" +
	"\vCreateBrand\x12(.service.goods.api.goods.v1.BrandRequest\x1a-.service.goods.api.goods.v1.BrandInfoResponse\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/brands\x12s\n" +
	"\vDeleteBrand\x12(.service.goods.api.goods.v1.BrandRequest\x1a!.service.goods.api.goods.v1.Empty\"\x17\x82\xd3\xe4\x93\x02\x11*\x0f/v1/brands/{id}\x12v\n" +
	"\vUpdateBrand\x12(.service.goods.api.goods.v1.BrandRequest\x1a!.service.goods.api.goods.v1.Empty\"\x1a\x82\xd3\xe4\x93\x02\x14:\x01*\x1a\x0f/v1/brands/{id}\x12t\n" +
	"\n" +
	"BannerList\x12!.service.goods.api.goods.v1.Empty\x1a..service.goods.api.goods.v1.BannerListResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/banners\x12}\n" +
	"\fCreateBanner\x12).service.goods.api.goods.v1.BannerRequest\x1a*.service.goods.api.goods.v1.BannerResponse\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/banners\x12v\n" +
	"\fDeleteBanner\x12).service.goods.api.goods.v1.BannerRequest\x1a!.service.goods.api.goods.v1.Empty\"\x18\x82\xd3\xe4\x93\x02\x12*\x10/v1/banners/{id}\x12y\n" +
	"\fUpdateBanner\x12).service.goods.api.goods.v1.BannerRequest\x1a!.service.goods.api.goods.v1.Empty\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\x1a\x10/v1/banners/{id}\x12\x9f\x01\n" +
	"\x11CategoryBrandList\x126.service.goods.api.goods.v1.CategoryBrandFilterRequest\x1a5.service.goods.api.goods.v1.CategoryBrandListResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/category-brands\x12\x9a\x01\n" +
	"\x14GetCategoryBrandList\x12/.service.goods.api.goods.v1.CategoryInfoRequest\x1a-.service.goods.api.goods.v1.BrandListResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/v1/categories/{id}/brands\x12\x9a\x01\n" +
	"\x13CreateCategoryBrand\x120.service.goods.api.goods.v1.CategoryBrandRequest\x1a1.service.goods.api.goods.v1.CategoryBrandResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/category-brands\x12\x8c\x01\n" +
	"\x13DeleteCategoryBrand\x120.service.goods.api.goods.v1.CategoryBrandRequest\x1a!.service.goods.api.goods.v1.Empty\" \x82\xd3\xe4\x93\x02\x1a*\x18/v1/category-brands/{id}\x12\x8f\x01\n" +
	"\x13UpdateCategoryBrand\x120.service.goods.api.goods.v1.CategoryBrandRequest\x1a!.service.goods.api.goods.v1.Empty\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\x1a\x18/v1/category-brands/{id}BC\n" +
	"\x1aservice.goods.api.goods.v1P\x01Z#mshop/service/goods/api/goods/v1;v1b\x06proto3"

var file_goods_v1_service_proto_goTypes = []any{
	(*GoodsFilterRequest)(nil),         // 0: service.goods.api.goods.v1.GoodsFilterRequest
	(*BatchGoodsIdInfo)(nil),           // 1: service.goods.api.goods.v1.BatchGoodsIdInfo
	(*CreateGoodsInfo)(nil),            // 2: service.goods.api.goods.v1.CreateGoodsInfo
	(*DeleteGoodsInfo)(nil),            // 3: service.goods.api.goods.v1.DeleteGoodsInfo
	(*GoodInfoRequest)(nil),            // 4: service.goods.api.goods.v1.GoodInfoRequest
	(*Empty)(nil),                      // 5: service.goods.api.goods.v1.Empty
	(*CategoryListRequest)(nil),        // 6: service.goods.api.goods.v1.CategoryListRequest
	(*CategoryInfoRequest)(nil),        // 7: service.goods.api.goods.v1.CategoryInfoRequest
	(*DeleteCategoryRequest)(nil),      // 8: service.goods.api.goods.v1.DeleteCategoryRequest
	(*BrandFilterRequest)(nil),         // 9: service.goods.api.goods.v1.BrandFilterRequest
	(*BrandRequest)(nil),               // 10: service.goods.api.goods.v1.BrandRequest
	(*BannerRequest)(nil),              // 11: service.goods.api.goods.v1.BannerRequest
	(*CategoryBrandFilterRequest)(nil), // 12: service.goods.api.goods.v1.CategoryBrandFilterRequest
	(*CategoryBrandRequest)(nil),       // 13: service.goods.api.goods.v1.CategoryBrandRequest
	(*GoodsListResponse)(nil),          // 14: service.goods.api.goods.v1.GoodsListResponse
	(*GoodsInfoResponse)(nil),          // 15: service.goods.api.goods.v1.GoodsInfoResponse
	(*CategoryListResponse)(nil),       // 16: service.goods.api.goods.v1.CategoryListResponse
	(*SubCategoryListResponse)(nil),    // 17: service.goods.api.goods.v1.SubCategoryListResponse
	(*CategoryInfoResponse)(nil),       // 18: service.goods.api.goods.v1.CategoryInfoResponse
	(*BrandListResponse)(nil),          // 19: service.goods.api.goods.v1.BrandListResponse
	(*BrandInfoResponse)(nil),          // 20: service.goods.api.goods.v1.BrandInfoResponse
	(*BannerListResponse)(nil),         // 21: service.goods.api.goods.v1.BannerListResponse
	(*BannerResponse)(nil),             // 22: service.goods.api.goods.v1.BannerResponse
	(*CategoryBrandListResponse)(nil),  // 23: service.goods.api.goods.v1.CategoryBrandListResponse
	(*CategoryBrandResponse)(nil),      // 24: service.goods.api.goods.v1.CategoryBrandResponse
}
var file_goods_v1_service_proto_depIdxs = []int32{
	0,  // 0: service.goods.api.goods.v1.Goods.GoodsList:input_type -> service.goods.api.goods.v1.GoodsFilterRequest
	1,  // 1: service.goods.api.goods.v1.Goods.BatchGetGoods:input_type -> service.goods.api.goods.v1.BatchGoodsIdInfo
	2,  // 2: service.goods.api.goods.v1.Goods.CreateGoods:input_type -> service.goods.api.goods.v1.CreateGoodsInfo
	3,  // 3: service.goods.api.goods.v1.Goods.DeleteGoods:input_type -> service.goods.api.goods.v1.DeleteGoodsInfo
	2,  // 4: service.goods.api.goods.v1.Goods.UpdateGoods:input_type -> service.goods.api.goods.v1.CreateGoodsInfo
	4,  // 5: service.goods.api.goods.v1.Goods.GetGoodsDetail:input_type -> service.goods.api.goods.v1.GoodInfoRequest
	5,  // 6: service.goods.api.goods.v1.Goods.GetAllCategorysList:input_type -> service.goods.api.goods.v1.Empty
	6,  // 7: service.goods.api.goods.v1.Goods.GetSubCategory:input_type -> service.goods.api.goods.v1.CategoryListRequest
	7,  // 8: service.goods.api.goods.v1.Goods.CreateCategory:input_type -> service.goods.api.goods.v1.CategoryInfoRequest
	8,  // 9: service.goods.api.goods.v1.Goods.DeleteCategory:input_type -> service.goods.api.goods.v1.DeleteCategoryRequest
	7,  // 10: service.goods.api.goods.v1.Goods.UpdateCategory:input_type -> service.goods.api.goods.v1.CategoryInfoRequest
	9,  // 11: service.goods.api.goods.v1.Goods.BrandList:input_type -> service.goods.api.goods.v1.BrandFilterRequest
	10, // 12: service.goods.api.goods.v1.Goods.CreateBrand:input_type -> service.goods.api.goods.v1.BrandRequest
	10, // 13: service.goods.api.goods.v1.Goods.DeleteBrand:input_type -> service.goods.api.goods.v1.BrandRequest
	10, // 14: service.goods.api.goods.v1.Goods.UpdateBrand:input_type -> service.goods.api.goods.v1.BrandRequest
	5,  // 15: service.goods.api.goods.v1.Goods.BannerList:input_type -> service.goods.api.goods.v1.Empty
	11, // 16: service.goods.api.goods.v1.Goods.CreateBanner:input_type -> service.goods.api.goods.v1.BannerRequest
	11, // 17: service.goods.api.goods.v1.Goods.DeleteBanner:input_type -> service.goods.api.goods.v1.BannerRequest
	11, // 18: service.goods.api.goods.v1.Goods.UpdateBanner:input_type -> service.goods.api.goods.v1.BannerRequest
	12, // 19: service.goods.api.goods.v1.Goods.CategoryBrandList:input_type -> service.goods.api.goods.v1.CategoryBrandFilterRequest
	7,  // 20: service.goods.api.goods.v1.Goods.GetCategoryBrandList:input_type -> service.goods.api.goods.v1.CategoryInfoRequest
	13, // 21: service.goods.api.goods.v1.Goods.CreateCategoryBrand:input_type -> service.goods.api.goods.v1.CategoryBrandRequest
	13, // 22: service.goods.api.goods.v1.Goods.DeleteCategoryBrand:input_type -> service.goods.api.goods.v1.CategoryBrandRequest
	13, // 23: service.goods.api.goods.v1.Goods.UpdateCategoryBrand:input_type -> service.goods.api.goods.v1.CategoryBrandRequest
	14, // 24: service.goods.api.goods.v1.Goods.GoodsList:output_type -> service.goods.api.goods.v1.GoodsListResponse
	14, // 25: service.goods.api.goods.v1.Goods.BatchGetGoods:output_type -> service.goods.api.goods.v1.GoodsListResponse
	15, // 26: service.goods.api.goods.v1.Goods.CreateGoods:output_type -> service.goods.api.goods.v1.GoodsInfoResponse
	5,  // 27: service.goods.api.goods.v1.Goods.DeleteGoods:output_type -> service.goods.api.goods.v1.Empty
	5,  // 28: service.goods.api.goods.v1.Goods.UpdateGoods:output_type -> service.goods.api.goods.v1.Empty
	15, // 29: service.goods.api.goods.v1.Goods.GetGoodsDetail:output_type -> service.goods.api.goods.v1.GoodsInfoResponse
	16, // 30: service.goods.api.goods.v1.Goods.GetAllCategorysList:output_type -> service.goods.api.goods.v1.CategoryListResponse
	17, // 31: service.goods.api.goods.v1.Goods.GetSubCategory:output_type -> service.goods.api.goods.v1.SubCategoryListResponse
	18, // 32: service.goods.api.goods.v1.Goods.CreateCategory:output_type -> service.goods.api.goods.v1.CategoryInfoResponse
	5,  // 33: service.goods.api.goods.v1.Goods.DeleteCategory:output_type -> service.goods.api.goods.v1.Empty
	5,  // 34: service.goods.api.goods.v1.Goods.UpdateCategory:output_type -> service.goods.api.goods.v1.Empty
	19, // 35: service.goods.api.goods.v1.Goods.BrandList:output_type -> service.goods.api.goods.v1.BrandListResponse
	20, // 36: service.goods.api.goods.v1.Goods.CreateBrand:output_type -> service.goods.api.goods.v1.BrandInfoResponse
	5,  // 37: service.goods.api.goods.v1.Goods.DeleteBrand:output_type -> service.goods.api.goods.v1.Empty
	5,  // 38: service.goods.api.goods.v1.Goods.UpdateBrand:output_type -> service.goods.api.goods.v1.Empty
	21, // 39: service.goods.api.goods.v1.Goods.BannerList:output_type -> service.goods.api.goods.v1.BannerListResponse
	22, // 40: service.goods.api.goods.v1.Goods.CreateBanner:output_type -> service.goods.api.goods.v1.BannerResponse
	5,  // 41: service.goods.api.goods.v1.Goods.DeleteBanner:output_type -> service.goods.api.goods.v1.Empty
	5,  // 42: service.goods.api.goods.v1.Goods.UpdateBanner:output_type -> service.goods.api.goods.v1.Empty
	23, // 43: service.goods.api.goods.v1.Goods.CategoryBrandList:output_type -> service.goods.api.goods.v1.CategoryBrandListResponse
	19, // 44: service.goods.api.goods.v1.Goods.GetCategoryBrandList:output_type -> service.goods.api.goods.v1.BrandListResponse
	24, // 45: service.goods.api.goods.v1.Goods.CreateCategoryBrand:output_type -> service.goods.api.goods.v1.CategoryBrandResponse
	5,  // 46: service.goods.api.goods.v1.Goods.DeleteCategoryBrand:output_type -> service.goods.api.goods.v1.Empty
	5,  // 47: service.goods.api.goods.v1.Goods.UpdateCategoryBrand:output_type -> service.goods.api.goods.v1.Empty
	24, // [24:48] is the sub-list for method output_type
	0,  // [0:24] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_goods_v1_service_proto_init() }
func file_goods_v1_service_proto_init() {
	if File_goods_v1_service_proto != nil {
		return
	}
	file_goods_v1_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_goods_v1_service_proto_rawDesc), len(file_goods_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_goods_v1_service_proto_goTypes,
		DependencyIndexes: file_goods_v1_service_proto_depIdxs,
	}.Build()
	File_goods_v1_service_proto = out.File
	file_goods_v1_service_proto_goTypes = nil
	file_goods_v1_service_proto_depIdxs = nil
}
