// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"mshop/service/order/internal/biz"
	"mshop/service/order/internal/conf"
	"mshop/service/order/internal/data"
	"mshop/service/order/internal/server"
	"mshop/service/order/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, services *conf.Services, logger log.Logger) (*kratos.App, func(), error) {
	db, err := data.NewDB(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	goodsClient, err := data.NewGoodsServiceClient(services, logger)
	if err != nil {
		return nil, nil, err
	}
	inventoryClient, err := data.NewInventoryServiceClient(services, logger)
	if err != nil {
		return nil, nil, err
	}
	client, cleanup, err := data.NewRedisClient(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup2, err := data.NewData(confData, goodsClient, inventoryClient, client, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	orderUsecase := biz.NewOrderUsecase(db, dataData, logger)
	orderService := service.NewOrderService(orderUsecase)
	grpcServer := server.NewGRPCServer(confServer, orderService, logger)
	httpServer := server.NewHTTPServer(confServer, orderService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
