// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.11
// source: order/v1/service.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_order_v1_service_proto protoreflect.FileDescriptor

const file_order_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x16order/v1/service.proto\x12\x10service.order.v1\x1a\x16order/v1/message.proto\x1a\x1cgoogle/api/annotations.proto2\xe7\x06\n" +
	"\x05Order\x12i\n" +
	"\fCartItemList\x12\x1a.service.order.v1.UserInfo\x1a&.service.order.v1.CartItemListResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/cart/{id}\x12p\n" +
	"\x0eCreateCartItem\x12!.service.order.v1.CartItemRequest\x1a&.service.order.v1.ShopCartInfoResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/v1/cart\x12f\n" +
	"\x0eUpdateCartItem\x12!.service.order.v1.CartItemRequest\x1a\x17.service.order.v1.Empty\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\x1a\r/v1/cart/{id}\x12c\n" +
	"\x0eDeleteCartItem\x12!.service.order.v1.CartItemRequest\x1a\x17.service.order.v1.Empty\"\x15\x82\xd3\xe4\x93\x02\x0f*\r/v1/cart/{id}\x12h\n" +
	"\vCreateOrder\x12\x1e.service.order.v1.OrderRequest\x1a#.service.order.v1.OrderInfoResponse\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/order\x12i\n" +
	"\tOrderList\x12$.service.order.v1.OrderFilterRequest\x1a#.service.order.v1.OrderListResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/order\x12p\n" +
	"\vOrderDetail\x12\x1e.service.order.v1.OrderRequest\x1a).service.order.v1.OrderInfoDetailResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/order/{id}\x12m\n" +
	"\x11UpdateOrderStatus\x12\x1d.service.order.v1.OrderStatus\x1a\x17.service.order.v1.Empty\" \x82\xd3\xe4\x93\x02\x1a:\x01*\x1a\x15/v1/order/{id}/statusBC\n" +
	"\x1aservice.order.api.order.v1P\x01Z#mshop/service/order/api/order/v1;v1b\x06proto3"

var file_order_v1_service_proto_goTypes = []any{
	(*UserInfo)(nil),                // 0: service.order.v1.UserInfo
	(*CartItemRequest)(nil),         // 1: service.order.v1.CartItemRequest
	(*OrderRequest)(nil),            // 2: service.order.v1.OrderRequest
	(*OrderFilterRequest)(nil),      // 3: service.order.v1.OrderFilterRequest
	(*OrderStatus)(nil),             // 4: service.order.v1.OrderStatus
	(*CartItemListResponse)(nil),    // 5: service.order.v1.CartItemListResponse
	(*ShopCartInfoResponse)(nil),    // 6: service.order.v1.ShopCartInfoResponse
	(*Empty)(nil),                   // 7: service.order.v1.Empty
	(*OrderInfoResponse)(nil),       // 8: service.order.v1.OrderInfoResponse
	(*OrderListResponse)(nil),       // 9: service.order.v1.OrderListResponse
	(*OrderInfoDetailResponse)(nil), // 10: service.order.v1.OrderInfoDetailResponse
}
var file_order_v1_service_proto_depIdxs = []int32{
	0,  // 0: service.order.v1.Order.CartItemList:input_type -> service.order.v1.UserInfo
	1,  // 1: service.order.v1.Order.CreateCartItem:input_type -> service.order.v1.CartItemRequest
	1,  // 2: service.order.v1.Order.UpdateCartItem:input_type -> service.order.v1.CartItemRequest
	1,  // 3: service.order.v1.Order.DeleteCartItem:input_type -> service.order.v1.CartItemRequest
	2,  // 4: service.order.v1.Order.CreateOrder:input_type -> service.order.v1.OrderRequest
	3,  // 5: service.order.v1.Order.OrderList:input_type -> service.order.v1.OrderFilterRequest
	2,  // 6: service.order.v1.Order.OrderDetail:input_type -> service.order.v1.OrderRequest
	4,  // 7: service.order.v1.Order.UpdateOrderStatus:input_type -> service.order.v1.OrderStatus
	5,  // 8: service.order.v1.Order.CartItemList:output_type -> service.order.v1.CartItemListResponse
	6,  // 9: service.order.v1.Order.CreateCartItem:output_type -> service.order.v1.ShopCartInfoResponse
	7,  // 10: service.order.v1.Order.UpdateCartItem:output_type -> service.order.v1.Empty
	7,  // 11: service.order.v1.Order.DeleteCartItem:output_type -> service.order.v1.Empty
	8,  // 12: service.order.v1.Order.CreateOrder:output_type -> service.order.v1.OrderInfoResponse
	9,  // 13: service.order.v1.Order.OrderList:output_type -> service.order.v1.OrderListResponse
	10, // 14: service.order.v1.Order.OrderDetail:output_type -> service.order.v1.OrderInfoDetailResponse
	7,  // 15: service.order.v1.Order.UpdateOrderStatus:output_type -> service.order.v1.Empty
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_order_v1_service_proto_init() }
func file_order_v1_service_proto_init() {
	if File_order_v1_service_proto != nil {
		return
	}
	file_order_v1_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_v1_service_proto_rawDesc), len(file_order_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_v1_service_proto_goTypes,
		DependencyIndexes: file_order_v1_service_proto_depIdxs,
	}.Build()
	File_order_v1_service_proto = out.File
	file_order_v1_service_proto_goTypes = nil
	file_order_v1_service_proto_depIdxs = nil
}
