// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"mshop/service/inventory/internal/biz"
	"mshop/service/inventory/internal/conf"
	"mshop/service/inventory/internal/data"
	"mshop/service/inventory/internal/server"
	"mshop/service/inventory/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, services *conf.Services, logger log.Logger) (*kratos.App, func(), error) {
	db, err := data.NewDB(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	goodsClient, err := data.NewGoodsServiceClient(services, logger)
	if err != nil {
		return nil, nil, err
	}
	client, cleanup, err := data.NewRedisClient(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	redsync := data.NewRedsync(client)
	dataData, cleanup2, err := data.NewData(confData, goodsClient, client, redsync, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	inventoryUsecase := biz.NewInventoryUsecase(db, dataData, logger)
	inventoryService := service.NewInventoryService(inventoryUsecase)
	grpcServer := server.NewGRPCServer(confServer, inventoryService, logger)
	httpServer := server.NewHTTPServer(confServer, inventoryService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
